type: pipeline_definition
product: Liberty
name: Test CI Orchestrator
description: "Run a Pipeline against the OpenLiberty/for-automation-testing repository."
triggers:
- type: github
  description: "Runs a Pipeline using a PR comment request."
  triggerName: "test-for-automation-testing"
  triggerRank: 50
  groups: ["CSD"]
  keyword: "!build"
  aliasKeywords:
    - "#build"

steps:
- stepName: PR Changes
  workType: PRChangesDetection
  timeoutInMinutes: 30
  properties:
    githubPRApi: ${github_pr_api}
    githubPRNumber: ${github_pr_number}
